NumPy is a library that provides 1,2, and n-dimensional arrays, as well as sorting, calculation, and other algorithms to perform on them.
These arrays can be represented and manipulated, visualizations are provided by matplotlib. 

In [1]:
import numpy as np
import matplotlib as plt

After this practice, one should be able to understand the difference between 1,2, and n-dimensional arrays in NumPy; Understand how to apply linear algebra operations to n-dimensional arrays without using for-loops; understand axis and shape properties for n-dimensional arrays. 

NumPy's main feature is the homogenous. multidimensional array. It is a table of elements (usually numbers) all of the same type, indexed by a tuple of non-negative integers.
-in NumPy, dimensions are called axes (plural of axis)

The array for coords of point in 3D space below has one axis. This axis has 3 elements, so it is an axis of length 3 (1 row by 3 columns):

[1,2,3]

The array below has 2 axes. The first axis has a length of 2, and the second axis has a length of 3 (2 rows by 3 columns):

[[1, 2, 3],
 [4, 5, 6]]

NumPy's array class is called ndarray, and has the alias array.
-numpy.array is not the same as the Standard Python Library's array.array; STL handles 1-D arrays with less functionality.

important numpy.array attributes:
-ndarray.ndim -> # of axes (dimensions) of the array

-ndarray.shape -> dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). the length of the shape tuple, is therefore the # of axes, ndim

-ndarray.size -> the total number of elements of the array. This is equal to the product of the elements of shape.

-ndarray.dtype -> an object describing the type of elements in the array. One can create or specify dtypes using standard Python types. NumPy also provides its own types, such as numpy.int32, numpy.int16. and numpy.float64

-ndarray.itemsize -> the size in bytes of each element of the array. e.g., an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemszie 4 (=32/8). It's equal to ndarray.dtype.itemsize. (remember, a byte is 8 bits)

-ndarray.data -> the buffer containing the actual elements of the array. Normally, we won't need this attribute because we will access elements in an array using indexing facilitites.
Example below:

In [3]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.size

15

In [8]:
a.dtype

dtype('int64')

In [9]:
a.itemsize

8

In [10]:
a.data

In [11]:
type(a)

numpy.ndarray

In [12]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [13]:
type(b)

numpy.ndarray

ARRAY CREATION - there are several ways to create arrays, e.g. from a Python STL list / tuple using the array function.

 The type of resulting array is deduced from the type of elements in the sequences:

In [14]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b = np.array([1.3, 4.5, 6.7])
b.dtype

dtype('float64')

In [17]:
c = np.array(["one", "two", "three"])
c.dtype

dtype('<U5')

A frequent error comes from calling np.array() with multiple argument, rather than providing a single sequence as an argument:

In [ ]:
a = np.array(1,2,3,4) # Wrong

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [19]:
a = np.array([1,2,3,4]) # Correct

np.array transforms sequences of sequences into 2-D arrays, sequences of sequences of sequences to 3-D arrays, etc:

In [21]:
b = np.array([(1,2,3,4), (5,6,7,8)])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
b.ndim

2

In [ ]:
b.size